### ISSUE TITLE
bdr_replicate_ddl_command documentation either unclear, or the function has an unintended feature :D

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [2ndQuadrant/bdr#120]
Hi :)

[The documentation for bdr.bdr_replicate_ddl_command](http://bdr-project.org/docs/next/ddl-replication-statements.html), at least to me, seems to pretty clearly state that the function is to be used to replicate SQL commands whose outcome wouldn't otherwise be replicated, such as CREATE ROLE and similar global stuff.

What's not mentioned, though, is that doing something like `SELECT bdr.bdr_replicate_ddl_command('CREATE SCHEMA schemamema;');` will cause the DDL lock to **not be set**, which it otherwise would if one did just `CREATE SCHEMA schemamema;`.

This is perfect for our use case, as we'd like to be able to create new users (customers) and create a fresh schema for them without cancelling running transactions on other nodes and not blocking DML.

I'm just not entirely sure that this is intended, since the documentation doesn't seem to inform about this fact. I hope it **is** intended, because I'm happy about the behavior, but even if it is, it should probably be documented, perhaps even with a warning that you might e.g. do DDL on a subset of a group (if a node is temporarily down) which could leave it in a funky state.

Cheers :)

**Comment by ringerc** [comment]
On 2 September 2015 at 18:13, Daniel Smedegaard Buus <
notifications@github.com> wrote:

> I'm just not entirely sure that this is intended, since the documentation
> doesn't seem to inform about this fact. I hope it is intended, because I'm
> happy about the behavior, but even if it is, it should probably be
> documented, perhaps even with a warning that you might e.g. do DDL on a
> subset of a group (if a node is temporarily down) which could leave it in a
> funky state.
>

It is intended, but it's a very good point that it should be documented.

You won't do DDL on a subset of the group if a node is down. It's still
enqueued for later application. The problem is that if something
concurrently happens on the other node (say, during a network partition)
that causes it not to be able to apply that DDL, you're in trouble. For
example, if another node does a CREATE USER of the same user name.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
You should also avoid using it for DDL that changes table definitions,
because that might leave transactions unable to apply to the changed
table. The main purpose of the global DDL lock is to ensure that the
queues of committed transactions that are not yet applied are empty.
Otherwise an ALTER TABLE, DROP TABLE, etc, might render it impossible
to apply the old transactions to the new table definition.

I've tweaked the documentation to reflect that, as it's pretty
significant. The function used to take the DDL lock, so it didn't
matter, but that caused other issues.

**Comment by DanielSmedegaardBuus** [comment]
That's cool, thank you :) And thanks for pointing out that not all DDL might cause havoc, of course you're right. And in our current use case, it couldn't possibly, as we're creating a schema and a user that didn't exist before :)

Cheers, and have a nice weekend :+1:
