### ISSUE TITLE
Is it possible to optimize bdr_group_join if new node is pre pg_restored w/ identical db?

### ISSUE THREAD

**Issue by bhtek** [2ndQuadrant/bdr#128]
I am trying to add a new node over rather slow internet connection. Is it possible to pre pg_restore with a dump and have bdr do some checks and let it come online? Or MUST it always go through the pg_dump over wire which with the latency, becomes horribly slow and unusable?

**Comment by ringerc** [comment]
At this time you must let it do the dump and restore over the wire.

Those "some checks" are quite complicated to say the least, and there's no plan to implement them any time soon. We'd have to do a detailed database schema compare down to dropped columns, etc, and also have to do a diff/sync of the data rows.

Theoretically if the upstream database you're joining has been completely idle since you took the dump you could just restore the dump and carry on. We don't have a reliable way to ensure that though, since the dump doesn't contain any way to identify the moment in database history that it was taken. (The timestamp is not good enough). Anyway, BDR doesn't currently offer a way to skip the dump/restore phase, so you'd have to add that too.

You do make a good point, though, that while operation is tolerant of latency and network partitions, node bringup is somewhat less so.

The long term solution to this is planned to be:

* `pg_dump --schema-only` the schema
* `COPY` each table to the empty downstream tables using a group of parallel background workers

At this point we might then be able to add support for lazy sync, where the tables are not copied from the slot's snapshot but are instead loaded by compare and sync. That'd require someone to write that compare and sync code, too, though, and right now we have lots of higher priorities. The work item for that is #14 .

Bug #78 is also relevant, as is #77, since this is effectively "rejoin a parted node by syncing changes".

**Comment by ringerc** [comment]
I'm closing this issue since the it's a general question not a specific bug/feature. If you feel that the issues linked do not sufficiently cover the matter, please feel free to open an feature request issue for "join a node restored from a dump or re-join a parted node". Then link to the above issues, and to this one, in your new issue.

**Comment by ringerc** [comment]
BTW, if you're really keen on having this, I'd be willing to provide some guidance on how to implement it. You'd have to be willing to spend quite a bit of time learning how to do that though, including designing (or finding and repurposing) algorithms for the schema-compare and the data compare-and-sync.

**Comment by bhtek** [comment]
Thank you for the insightful reply. Yes, I am quite keen but am afraid that
my C/C++ is too rusty to be useful. I will follow your advice and file a
feature request.

Thanks again for the help.
