### ISSUE TITLE
Quick start documentation and apt repo docs contain multiple errors

### ISSUE THREAD

**Issue by henri-tremblay** [2ndQuadrant/bdr#144]
I went through the quick start guide and found multiple errors. As of now, I've not been able to install BDR at all. Here are some of the errors:
* 2.1: The curl on REL0_9_STABLE doesn't compile. Makefiles seems to include non-existing ones
* 2.1: The curl on next fails because pg_config isn't found
* 2.1: It could be useful to mention that git needs to be installed
* On http://packages.2ndquadrant.com/bdr/apt/. Only the udr package is mentioned. I guess for BDR I need postgresql-bdr-9.4-bdr-plugin but it doesn't seem to work
* On the same page, the packages won't install. Dependencies are missing. They agreed to instal by adding the postgresql repo http://apt.postgresql.org/pub/repos/apt/
* 2.3: track_commit_timestamp doesn't exist on PostgreSQL 9.4

**Comment by ringerc** [comment]
Good point. I haven't updated that script in some time. I've seen no sign people are using it or interested, and may just remove it. Source install instructions are at http://bdr-project.org/docs/stable/installation-source.html .

Good catch on the README in the packages repo. I'll delete it and redirect it to http://bdr-project.org/docs/stable/installation-packages.html .

Re "dependencies are missing": details please? Exact commands run and error messages? For UDR you need the PGDG repository too, since it's built against PGDG PostgreSQL. That needs to be made more explicit. The BDR extension (`postgresql-bdr-9.4-bdr`) depends on the bdr-patched server and should install fine standalone.

Part of the issue here is that UDR has had limited resources available, with attention focused almost entirely on BDR.

Re `track_commit_timestamp`, it's added by the BDR patchset to the BDR-patched PostgreSQL. The quickstart is for setting up BDR. It should really be updated to make that more obvious now that we have UDR as well.

All this is receiving less attention that it could be because of the ongoing work on getting pglogical (which is derived from bdr) into PostgreSQL.

**Comment by ringerc** [comment]
Just noticed you're talking about the apt repository. I haven't had any involvement in that. Disregard my comments re BDR working standalone; I haven't checked that for apt packages.

I'll have to update the docs for the apt packages; thanks for pointing out that they need attention. 100% of customers use RHEL/CentOS, so that's the priority for BDR, but the apt package info needs to be complete enough to reasonably use.

**Comment by henri-tremblay** [comment]
I agree that the sample is not really useful. After a huge fight, I managed to have a working setup. It's a shame because it isn't that complicated in the end. On thing that blocked me was the `dsn`. Because for a real test, having the different VMs talking to one another is a must.

I also confirm that the postgresql apt repository is required. Because `postgresql-bdr-9.4` wants `postgresql-bdr-client-9.4` who wants `libpq5` which is not available.

In order to be helpful, here is my personal procedure:
* Have two plain ubuntu VMs (14.04 in my case, running with vagrant and virtualbox)
* On both do as `root`
```
echo "deb http://packages.2ndquadrant.com/bdr/apt/ trusty-2ndquadrant main" > /etc/apt/sources.list.d/2ndquadrant.list
wget --quiet -O - http://packages.2ndquadrant.com/bdr/apt/AA7A6805.asc | sudo apt-key add -

echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

apt-get update
apt-get install -y postgresql-bdr-9.4 postgresql-bdr-9.4-bdr-plugin
```
* On both, replace the content of `/etc/postgresql/9.4/main/pg_hba.conf` by
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer
host    all             all             0.0.0.0/0               md5
local   replication     postgres                                peer
host    replication     postgres        0.0.0.0/0               md5
```
* On both, modify  `/etc/postgresql/9.4/main/postgresql.conf` to have
```
listen_addresses = '*'
shared_preload_libraries = 'bdr'
wal_level = 'logical'
track_commit_timestamp = on
max_connections = 100
max_wal_senders = 10
max_replication_slots = 10
max_worker_processes = 10
```
* Then switch user `su - postgres`
* Create the DB: `createdb -T template0 bdrdemo`
* Connect with psql `psql dbrdemo`
* Install the required extensions:
```
create extension btree_gist;
create extension bdr;
```
* Set a password to postgres `alter role postgres with password 'password';`
* Then, the grand final. On node one:
```
select bdr.bdr_group_create(local_node_name := 'node1', node_external_dsn := 'host=ip_of_node1 password=password dbname=bdrdemo');
select bdr.bdr_node_join_wait_for_ready();
```
* And on node two:
```
select bdr.bdr_group_join(local_node_name := 'node2', node_external_dsn := 'host=id_of_node2 password=password dbname=bdrdemo', join_using_dsn := 'host=id_of_node1 password=password dbname=bdrdemo');
select bdr.bdr_node_join_wait_for_ready();
```
Job done.

You can now create tables and fill them with data. It should replicate.

**Comment by ringerc** [comment]
On 25 November 2015 at 02:43, Henri Tremblay <notifications@github.com>
wrote:

> I agree that the sample is not really useful. After a huge fight, I
> managed to have a working setup. It's a shame because it isn't that
> complicated in the end. On thing that blocked me was the dsn. Because for
> a real test, having the different VMs talking to one another is a must.
>

What about the DSN was an issue?

People seem to get confused by libpq connection strings, but I'm not really
sure how to explain it better in the docs without adding a great deal of
information unrelated to BDR its self.

> I also confirm that the postgresql apt repository is required. Because
> postgresql-bdr-9.4 wants postgresql-bdr-client-9.4 who wants libpq5 which
> is not available.
>

Ah, that makes sense. apt.postgresql.org packages libpq separately, unlike
yum.postgresql.org, and BDR avoids publishing a conflicting libpq.

I'll amend the docs.

(I didn't do the apt packaging, as you can no doubt tell).

> In order to be helpful, here is my personal procedure
>

Thanks. That's useful, especially since it also shows me the logical
chain-of-thought for someone who hasn't been deep in the guts of BDR for
way, way too long now ;)


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by henri-tremblay** [comment]
The `dsn` because I had no idea what it was and the term is not that well documented on postgresql side. So it took me some time to figure out the format to use for an md5 authentication. But indeed, it is unrelated with BDR. A link to a doc explaining what is a `dsn` should be enough. And also some definitions. E.g.:
* local_node_name: The name of this node. Could be anything but should be unique in the bdr group (I guess)
* node_external_dsn: The dsn to use to connect to this node
* join_using_dsn: The dsn to connect to a node already in the bdr group

**Comment by jonranes** [comment]
Also I think people setting up distributed are going to want to not have passwords in their database and use trust for replication which is normal.  This get's tricky with this setup because of the local connection check which is going to leave you with the below when running bdr_group_create.

FATAL:  could not connect to the server in non-replication mode

I would be sure to add for distributed a sample pg_hba like below where 10.0.0.1 is the first node and 10.0.0.2 is the second.  Notice the trust connection for the bdr user for the same machine the pg_hba.conf is on...
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer

hostssl all             bdrsu           10.0.0.2/32	            trust
hostssl all             bdrsu           10.0.0.1/32	            trust

local   replication     bdrsu                                   peer
hostssl replication     bdrsu           10.0.0.2/32             trust
```
where bdsr user is created with
```
CREATE ROLE upbdr LOGIN SUPERUSER REPLICATION VALID UNTIL 'infinity';
```

**Comment by ringerc** [comment]
If you want to use passwords you can create a `.pgpass` file in the `postgres` user's home directory, or wherever the user that BDR runs under lives.

I agree we could define `dsn` better.
