### ISSUE TITLE
Standalone BDR node (single-node support)

### ISSUE THREAD

**Issue by eloycoto** [2ndQuadrant/bdr#158]
Hi, 

Does BDR have any way to run a node alone? I explain my problem, from our dev pipeline we create some SQL migrations but sometimes our devs make a mistake and add ADD COLUMN.. DEFAULT in the migrations and this broke the system. 

I want to run BDR node alone that will raise an error in case of any invalid SQL query. Is this possible? Or I need to run more than one node? 

I test to create a new group and keep the node alone, but I have the DDL error.
Regards

**Comment by ringerc** [comment]
> Does BDR have any way to run a node alone?

No, it does not. Global sequences require at least one node, as does the global DDL locking feature.

It's technically feasible to add support for standalone nodes and would be nice to have, but we don't have the development time/resources when there are so many higher priorities. If you'd like to look into implementing it I can give you some pointers on where you'd need to start.

> I want to run BDR node alone that will raise an error in case of any invalid SQL query. Is this possible? Or I need to run more than one node?

You'll need more than one node.

You would anyway, since you'd want to sanity check your migration results and make sure they applied with no errors on the other node, i.e. replicated correctly. Otherwise you'd be testing something other than what you're really running.

> I test to create a new group and keep the node alone, but I have the DDL error.

"The DDL error".

Details?

**Comment by eloycoto** [comment]
Hey @ringerc 

I'm quite busy at the moment, so I can't not spend time on that. But I made a small and dirty docker image to test on CI that migrations won't fail. 

https://hub.docker.com/r/eloycoto/postgresl_bdr/

When I have time, (hope in 3/4 weeks) I'll check if I can do something.

Regards

**Comment by ringerc** [comment]
Thanks. I know the feeling re busy. I'm somewhere beyond that and into "ridiculous".

**Comment by ringerc** [comment]
Done in 2.0.
