### ISSUE TITLE
Replication INCREASE/DECREASE of column value

### ISSUE THREAD

**Issue by derkan** [2ndQuadrant/bdr#164]
Hi,
I'm using BDR version `0.10.0-2016-03-01-72f8593`. And I have two db nodes `db1` and `db2`.
Here is my test for value increasing(same logic for decreasing):

1-On node `db1`

```sql
CREATE TABLE bal(
   id INTEGER NOT NULL PRIMARY KEY
   balance DOUBLE PRECISON NOT NULL DEFAULT 0.0
)
```

2-On `db1`:

```sql
INSERT INTO bal VALUES(1, 10.0);
```
Now balance on both instances is *10.0*

3-And after setting balance on `db1`, I shutdown `db2`

4-On `db1` node again:

```sql
UPDATE bal SET balance = balance+1 WHERE id=1;
```
Now balance on `db1` is *11.0*.

5-And after updating balance on `db1`, I *shutdown `db1`* and *open `db2`*.

6-On `db2` node:

```sql
UPDATE bal SET balance = balance+2 WHERE id=1;
```
Now balance on `db1` is *12.0*.

7-Everything is normal until here. Now I open `db1` instance. What I am expecting is to get balance as `13.0`. (+1 from **step 4** and +2 from **step 6**). But when I check table it is:

```sql
SELECT * FROM balance;
 id | balance 
----+---------
  1 |      12
```
This means that value is overwritten from `db2` when I open `db1` as that was the last update.

This will lead to big problems where balance *inc/dec* operations are applied with slow connection between nodes. Is there a way to resolve this problem?

Regards,
Erkan D.

**Comment by ringerc** [comment]
On 2 March 2016 at 01:38, Erkan Durmus <notifications@github.com> wrote:

> This will lead to big problems where balance *inc/dec* operations are
> applied with slow connection between nodes. Is there a way to resolve this
> problem?
>

What you're describing is absolutely normal for an asynchronous
multi-master replication system and is a consequence of the lack of locking
between nodes. To solve it we'd need to support special data types that
*merge* states from different nodes. There are no plans for such support,
but of course patches are welcome. It's not trivial to write them since
you'd have to add index opclass support etc too.

Your application must deal with this externally. If you can't, then
asynchronous multimaster is not for you and you need a more tightly coupled
synchronous solution with a global lock manager and global transaction
manager, like Postgres-XL.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment]
Closed - not a bug.

**Comment by derkan** [comment]
Thanks for your response. As far as I know PostgreXL is suitable if all nodes are in same LAN with fast network. But your BDR solution is better as I  need  inter-datacenter replication. To investigate problem, I checked logical replication slots to see how the SQL's are logged.
SQL's are not logged as is, instead last retrieved value is put as params.
For example the following SQL
```sql
UPDATE bal SET balance = balance+1 WHERE id=1;
```
is logged as (if current value of bal.balance is 10):
```sql
table public.bal: UPDATE: id[integer]:1 bal[balance]:11
```
So SQL is run as if called like:
```sql
UPDATE bal SET balance = 11 WHERE id=1;
```
That's why it is overriding value each time, instead of increasing it.(That raising problem of `lost update phenomena`)

You're right we can not solve this situation, our app logic should be changed.

Regards
