### ISSUE TITLE
Some of the nodes starts to replicate only after 2 hours after network problems

### ISSUE THREAD

**Issue by robert-hegedus** [2ndQuadrant/bdr#170]
My setup is PostgreSQL-BDR on 4 server with the same configuration.

The problem is that, after network problems (e.g. connection lost for some minutes), some of the nodes starts to replicate in some seconds again, but other nodes starts to replicate only after 2 hours.

I couldn't find any configuration which defines this 2 hours delay thing.

I see the following lines when im monitoring replication slots:

slot_name | database | active | retained_bytes

bdr_16385_6255603470654648304_1_16385__ | mvcn | t | 56 bdr_16385_6255603530602290326_1_16385__ | mvcn | f | 17640 bdr_16385_6255603501002479656_1_16385__ | mvcn | f | 17640

Any idea why this is happening?

**Comment by sym39** [comment]
Did you check the state of the connection with netstat for example (or ss)? You could check on both nodes if the connection is correctly established by checking if the remote port is still connected.

I remember having stale connections after a power off of node2. In this case, the connection was not cleanly closed by the postgres worker for node1 because it did not detect something was wrong, and netstat reports a connection to the remote node2 that had been power off.

A workaround could be to terminate the bg worker for which the connection is stale with pg_terminate_backend().

The time the connection stays stale is most probably dependent of keep alive options, see http://www.postgresql.org/docs/9.4/static/runtime-config-connection.html (tcp_keepalives_idle, tcp_keepalives_interval, tcp_keepalives_count)

Hope this helps,
Sylvain

**Comment by martinmarques** [comment]
Heh,

I had to do that precise procedure yesterday on a bdr node that had the
worker stuck (this is really hard to diagnose unless you poke at the
process with gdb or strace).

Terminating the worker made postgres start a new bdr worker for that
connection and start streaming again.

Regards,


2016-03-22 14:32 GMT-03:00 sym39 <notifications@github.com>:

> Did you check the state of the connection with netstat for example (or
> ss)? You could check on both nodes if the connection is correctly
> established by checking if the remote port is still connected.
>
> I remember having stale connections after a power off of node2. In this
> case, the connection was not cleanly closed by the postgres worker for
> node1 because it did not detect something was wrong, and netstat reports a
> connection to the remote node2 that had been power off.
>
> A workaround could be to terminate the bg worker for which the connection
> is stale with pg_terminate_backend().
>
> The time the connection stays stale is most probably dependent of keep
> alive options, see
> http://www.postgresql.org/docs/9.4/static/runtime-config-connection.html
> (tcp_keepalives_idle, tcp_keepalives_interval, tcp_keepalives_count)
>
> Hope this helps,
> Sylvain
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/2ndQuadrant/bdr/issues/170#issuecomment-199922865>
>



-- 

Martín Marqués                http://www.2ndQuadrant.com/
PostgreSQL Development, 24x7 Support, Training & Services

**Comment by robert-hegedus** [comment]
Hey!
Changing the value of tcp_keepalives_idle did not solved the problem, because postgre could not change the /proc/sys/net/ipv4/tcp_keepalive_time for some permission reason maybe, but i changed directly the value of /proc/sys/net/ipv4/tcp_keepalive_time, and it is solved the problem.
Thank you very much!
Kind Regards,
Robert

**Comment by ringerc** [comment]
Yeah, I think we need to add some discussion about keepalives to the docs.
Patches would be most welcome.

I'm aware that diagnosing progress can be difficult. The support for more
information about wait states in 9.6's pg_stat_activity will help when
we're able to upgrade, but we really need some better infrastructure for
monitoring and tracking replication progress. I don't expect to have time
to build it any time soon unfortunately.
