### ISSUE TITLE
Easier way of removing transction from queue

### ISSUE THREAD

**Issue by PJMODOS** [2ndQuadrant/bdr#181]

**Comment by ringerc** [comment]
After chat discussion I plan to add a feature to log the xact commit LSN and current change LSN on any error using an error context callback. A trace mode will also be added to log every change before apply.

Then the method of removing the xact from the queue simply becomes finding its LSN and advancing the replication identifier for that peer. A simple function can map the bdr nodeid to the replication identifier string and advance it.

This only works when you want to skip that xact and everything prior to it, but since you'll mainly be interested in the case where the xact to skip is causing an error this seems to be sufficient.

For the future (pglogical) it'd be nice to have something cleverer that can skip just one xact or an xact range, but this will do fine for now.
