### ISSUE TITLE
Inconsistent data after disconnect and node restart

### ISSUE THREAD

**Issue by jacobtonndorf** [2ndQuadrant/bdr#190]
Hi, I've discovered that, if two nodes gets disconnected and then restart during the disconnected time I end up with inconsistent data (those data which was edit between disconect and restart of the nodes).

How to test :

- create 2 nodes, create database and connect them via bdr
- `CREATE TABLE data( id serial NOT NULL, data text, CONSTRAINT data_pkey PRIMARY KEY (id))`
- `INSERT INTO data(id,data) VALUES(1,'test');`
- on node1 and node2 `select * from data;` :

>  id | data 
----+------
  1 | test
(1 row)

- disconnect the two nodes from each other (e.g. unplug network cable)
- on **node1** : `update data set data = 'from **node 1**' where id = 1;`
- on **node2** : `update data set data = 'from **node 2**' where id = 1;`
- now we will have something like on node 2:

>  id | data 
--+------
  1 | from node 2
(1 row)

- and corresponding "from node 1" on node 1
- then restart both nodes `pg_ctl restart` (with the correct parameters for your nodes) (e.g. power failure)
- reconnect the two nodes (plug in network cable)
- and now we will get 
- on **node1**:

> select * from data;
 id |    data     
----+-------------
  1 | from **node 2**
(1 row)

- and on **node2**:

> select * from data;
 id |    data     
----+-------------
  1 | from **node 1**
(1 row)

- so now we have different data on the nodes

note: if I don't execute `pg_ctl restart`, bdr works correct and produces a update-update conflict and i get consistent data

**Comment by mz407f** [comment]
I believe if you add: "connect_timeout=10 keepalives_idle=5 keepalives_interval=1" to the DSN line it solves this issue:  For instance:

``
DSN_ARGS="connect_timeout=10 keepalives_idle=5 keepalives_interval=1"
SELECT bdr.bdr_group_create(
  local_node_name   := '$DB_NODE',
  node_external_dsn := 'host=$DB_ADDR port=$DB_PORT user=$REP_USER password=$REP_PASS dbname=$DB_NAME $DSN_ARGS',
  replication_sets  := '{$DB_RSET}'
);

SELECT bdr.bdr_group_join(
  local_node_name   := '$DB_NODE',
  node_external_dsn := 'host=$DB_ADDR port=$DB_PORT user=$REP_USER password=$REP_PASS dbname=$DB_NAME $DSN_ARGS',
  join_using_dsn    := 'host=$DB_SEED port=$DB_PORT user=$REP_USER password=$REP_PASS dbname=$DB_NAME',
  replication_sets  := '{$DB_RSET}'
);
``

**Comment by ringerc** [comment]
That's an interesting issue. It suggests a possible conflict resolution
problem. I'll try to reproduce this locally.

Are the clocks synced between the nodes? It shouldn't really be necessary,
but it's a good idea, and useful to know.

**Comment by jacobtonndorf** [comment]
@mz407f I assume you are refer to this: #170  .. I run into this problem earlier and edited my system settings, otherwise it would start to replicate again after 2 hours. 

As you may noticed, the data from node **1** appears on node **2** (and the other way round), so the data is replicated to the other nodes

Maybe you should add this to your documentation.

@ringerc My two test nodes are one the same system (different ports), so the clocks are in "sync". 

It looks like bdr lost the information about the last edit date of the data after a postgres restart.

**Comment by ringerc** [comment]
Petr mentioned that there were some commit timestamp tracking bugs fixed as
part of getting commit timestamps into PostgreSQL 9.5 that might be related
to this.

I'll try to find some details. I'm not sure how practical it'll be to
backport a fix even if I can identify what exactly it was.

**Comment by curlyhaze** [comment]
We are encountering the same issue as @jacobtonndorf. We have a test setup of 2 nodes in a group, both on the same server and using 2 different Postgresql 9.4 instances. If we start with both nodes being sync'd.
1) Shut down node 2. 
2) Update row X in table Y with value A in node 1.
3) Shut down node 1.
4) Start node 2. 
5) Update Row X in table Y with value B in node 2. 
*6) RESTART (Stop, then Start) node 2.
7) Start node 1.

Once sync'd, the result:
- Node 1 row X in table Y will have value B (no entry in conflict table)
- Node 2 row X in table Y will have value A (no entry in conflict table)

This is wrong as source transaction for B was at a later time than transaction for A.

If we remove step 6 (restart of node 2) then Node 2 row X in table Y will keep it's value B and an entry will appear in the conflict table as expected. 

Our running hypothesis is that anytime a node is restarted, it looses it's ability (or doesn't look at past transactions) to tell the transaction time of the table data, so anything coming in from a remote node will blindly overwrite existing data as the conflict resolution logic doesn't see a problem because of the missing local time. This causes a visible problem for node 2. Also, even though node 1 ends up with the right value, it has the same issue of the incoming data from node 2 blindly overwriting. It just happens to be the correct result in that case, but not because the conflict code is running correctly. 

So, I'd like to get a little more information about the transaction time tracking mechanism. track_commit_timestamp = on means that every transaction will have time added to it's meta-data. The time is not held locally in my Table Y for my Row X, but rather by the system where it holds transaction meta-data. The system xmin held in Table Y Row X is used to reference the transaction commit time. Does the transaction meta-data get trashed on restart (is it persistent or in-memory only)? Is it not loaded/looked at by BDR on restart? Does BDR track times it sees post-restart from new transactions and new remote node data only?

I'm also guessing some of the functions performed by Vacuum will affect the ability to extrapolate transaction commit time data for tuples.

We have the requirement that older data can NEVER overwrite newer data, so the current conflict resolution depending on transaction commit timestamp seems like it has too many edge cases.

So currently it seems like the only safe way to deal with this is to have a timestamp column in Table Y which is set to NOW() in the update statements and do our own conflict resolution. I believe Triggers on the receiving node won't work so we will need to create a custom conflict handler. Management functions are well defined here http://bdr-project.org/docs/next/functions-conflict-handlers.html. However, are there any custom handler example available as we cannot find any info/prototype.

  
Any insight would be greatly appreciated.

**Comment by ringerc** [comment]
FWIW, I checked the history of 9.5 and 9.6 and didn't find anything that looked relevant. The issues only applied to the 9.5 version of the code, not the very different one in 9.4bdr.

It seems highly likely that there's an initialisation issue somewhere, but I honestly need a reproducible test case to make much progress in the available time.

**Comment by ringerc** [comment]
The issue turned up in upstream PostgreSQL, see https://commitfest.postgresql.org/11/834/ and https://www.postgresql.org/message-id/flat/ff10e34a-c85f-3e2b-f07f-c4c4c88fae8b@dalibo.com by @rjuju.

I've applied the fix to BDR as 6c934ba1434c289b58adf95677d02b8a5f7db591 .
