### ISSUE TITLE
What is the best way to create Primary Key on a large table in Postgresql 9.5?

### ISSUE THREAD

**Issue by rtammineni** [2ndQuadrant/bdr#231]
i have to create a primary key on a large table (~100Million records). What is the best and fastest way to create pkey? This column is a sequence column and i don't want to lock the table because this is highly transactional database.

**Comment by PJMODOS** [comment]
This is not really BDR question.
However something like this should do the job (provided the column is already set as not null):
```
CREATE UNIQUE INDEX CONCURRENTLY my_pkey_idx ON my_table (id_column);
ALTER TABLE my_table ADD CONSTRAINT my_pkey PRIMARY KEY USING INDEX my_pkey_idx;
```
That will do minimal locking (just quick lock to update the catalog).

**Comment by rtammineni** [comment]
Thanks Peter!

Sorry, i have used my previous link to post the question. 

I have to add the column, populate the data and then convert into primary key. Please let me know if you any suggestions.

**Comment by PJMODOS** [comment]
Oh that's going to be more fun.
The best way I know would be:
```
ALTER TABLE my_table ADD COLUMN newcol;
ALTER TABLE my_table ALTER COLUMN newcol SET DEFAULT nextval('my_seq');
UPDATE my_table SET newcol = nextval('my_seq');
VACUUM my_table;
ALTER TABLE my_table ALTER COLUMN newcol SET NOT NULL;
```
And then what I wrote above with the `CREATE UNIQUE INDEX CONCURRENTLY`.

There are two caveats though. The UPDATE will produce large amount of bloat which is why the VACUUM should be run afterwards. And the bigger problem is that the last command (the SET NOT NULL) will still lock, but there is no way around that, it will lock for duration of one sequential scan so it's potentially survivable even with 100M rows but it will definitely affect the transactions for a moment.

**Comment by rtammineni** [comment]
Thank you Peter!

Thats what exactly i am thinking.
