### ISSUE TITLE
"No primary key" warning is ambiguous

### ISSUE THREAD

**Issue by bneumeier** [2ndQuadrant/bdr#251]
Using BDR 1.0, when I create a BDR group on a database that contains tables that have no primary key, I get this warning message for each such table:

```
WARNING:  Table %I.%I has no PRIMARY KEY
HINT:  Tables without a PRIMARY KEY cannot be UPDATEd or DELETEd from, only INSERTed into. Add a PRIMARY KEY.
```

It would be very helpful if the warning actually named the schema and table name!

**Comment by ringerc** [comment]
On 12 October 2016 at 23:44, Brett Neumeier <notifications@github.com>
wrote:

> Using BDR 1.0, when I create a BDR group on a database that contains
> tables that have no primary key, I get this warning message for each such
> table:
>
> WARNING:  Table %I.%I has no PRIMARY KEY
> HINT:  Tables without a PRIMARY KEY cannot be UPDATEd or DELETEd from, only INSERTed into. Add a PRIMARY KEY.
>
> It would be very helpful if the warning actually named the schema and
> table name!
>
Ha, that's a good one.

Fixed in git bdr-plugin/next, REL1_0_STABLE and the 9.6 dev tree.

It's fairly minor and only arises when creating a BDR group, so the fix on
git master only applies to new BDR instances, i.e. anywhere you run CREATE
EXTENSION bdr after applying the fix and installing the updated extension.



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
