### ISSUE TITLE
bdr_init_copy fails with "The remote node is not configured as a BDR node."

### ISSUE THREAD

**Issue by internetuser2008** [2ndQuadrant/bdr#271]
Performing test on vm. 
Where I blow away primary nod1(5598), took node1 out from node2 bdr_nodes then attempting to add it back as new node3 using bdr_init_copy.

bdr_init_copy -D /data/2ndquadrant_bdr/bdr5598 -n node3 -d 'host=localhost port=5598 dbname=bdrdemo' -U postgres --local-dbname='host=localhost port=5599 dbname=bdrdemo'
bdr_init_copy: starting ...
Getting remote server identification ...
The remote node is not configured as a BDR node.

**Comment by ringerc** [comment]
On 15 December 2016 at 01:22, internetuser2008 <notifications@github.com>
wrote:

> Performing test on vm.
> Where I blow away primary nod1(5598), took node1 out from node2 bdr_nodes
> then adding back as new node3.
>
> bdr_init_copy -D /data/2ndquadrant_bdr/bdr5598 -n node3 -d 'host=localhost
> port=5598 dbname=bdrdemo' -U postgres --local-dbname='host=localhost
> port=5599 dbname=bdrdemo'
> bdr_init_copy: starting ...
> Getting remote server identification ...
> The remote node is not configured as a BDR node.
>
>
This isn't really a bug report.

Versions involved?

EXACT steps and commands run?

Relevant log output?

General questions may be asked on the BDR mailing list / forum at
https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list . I'm
closing this since it isn't a bug report I can follow up on in any useful
way.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
