### ISSUE TITLE
UDR: Synchronise sequences

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#28]
UDR doesn't sync sequences at all. An upstream sequence will advance but the replaying downstream's corresponding sequence won't move. If you then use UDR for fail-over, you'll find out that the downstream sequences don't match the table contents.

We can't fully sync sequences like BDR because we don't have sequence access methods. But we could use a mapping of `OWNED BY` sequences in the table cache and, if a replicated row is greater than the current value of the sequence locally, advance the sequence. We probably can't support `setval`.

**Comment by mattrobenolt** [comment]
Adding in a vote for having this ability in BDR as well.

Here's the use case:

* `n` number of nodes running, all configured as BDR.
* One of the nodes is elected to a "leader" of the cluster. What this means, is we add this node into pgbouncer or haproxy.
* Other nodes in the cluster are not accessible, and they are just acting as standby, so we can guarantee linearizability of the sequence.

Why would we do this?

* Cluster can be operated in a typical leader/follower fashion, with the added bonus of being able to elect a new leader without complicating failover semantics.

I'd assume conflict resolution would need to happen as well for this to handle the general case, and I can't see why the LWW pattern wouldn't work well here for the sequence too as well as row data.

Let me know if this makes sense. I'm experimenting with ways of setting up a nice HA leader/follower and BDR seems the most appealing (rather than UDR) since it would provide the most functionality while being the most hands-off because of DDL synchronizations.

**Comment by anarazel** [comment]
On 2015-05-31 14:45:22 -0700, Matt Robenolt wrote:
> Adding in a vote for having this ability in BDR as well.

If implemented for UDR it'll definitely also be available for UDR.

> * `n` number of nodes running, all configured as BDR.
> * One of the nodes is elected to a "leader" of the cluster. What this means, is we add this node into pgbouncer or haproxy.
> * Other nodes in the cluster are not accessible, and they are just acting as standby, so we can guarantee linearizability of the sequence.

Note that this is *not* necessarily sufficient for linearizability,
depending on your failover mechanism/leader election. Gets pretty close
though.

> Why would we do this?

Makes a lot of sense to me, and there's already people using bdr for
this kind of purpose.

**Comment by mattrobenolt** [comment]
> Note that this is *not* necessarily sufficient for linearizability,
depending on your failover mechanism/leader election. Gets pretty close
though.

That is true, and that's where the conflict resolution would come in with LWW. :) For our use case of that, that'd be an acceptable tradeoff that we're willing to accept.

**Comment by PJMODOS** [comment]
closing as UDR is deprecated in favour of pglogical
