### ISSUE TITLE
bdr exiting on queued drop - index does not exist

### ISSUE THREAD

**Issue by ayurkows** [2ndQuadrant/bdr#299]
I'm getting the below error on my replicated node, how can I skip just this one commit?

@2ndquadrant-ci 

```
2018-01-04 23:12:15 UTC [29104-1] ERROR:  relation "table.index" does not exist
2018-01-04 23:12:15 UTC [29104-2] CONTEXT:  apply QUEUED_DROP in commit 65/31B90B88, xid 251760170 commited at 2018-01-04 18:28:27.610445+00 (action #2) from node (6448074489615395734,1,16386)
2018-01-04 23:12:15 UTC [28912-132] LOG:  worker process: bdr (6472068144492059561,1,16386,)->bdr (6448074489615395734,1, (PID 29104) exited with exit code 1
2018-01-04 23:12:20 UTC [28912-133] LOG:  starting background worker process "bdr (6472068144492059561,1,16386,)->bdr (6448074489615395734,1,"
```
  
Note: I created the index concurrently, and then it was invalid which is why I was dropping it. This is likely why it wasnt on the other nodes, but now I'm stuck with nodes that aren't replicating properly.

**Comment by ayurkows** [comment]
I see the queued drop in bdr.bdr_queued_drops on the node I executed it on, and all other nodes are failing.

Based on the docs, I shouldn't remove this row.
http://bdr-project.org/docs/1.0/catalog-bdr-queued-drops.html

**Comment by ayurkows** [comment]
Would I also possibly be able to bdr.skip_ddl_replication and add the index so they can properly remove it?

**Comment by ayurkows** [comment]
The below fixed the issue! running on the other nodes now 🕺 

```
SET bdr.skip_ddl_locking = true;
SET bdr.skip_ddl_replication = true;
CREATE INDEX
SET bdr.skip_ddl_locking = false;
SET bdr.skip_ddl_replication = false;
```

**Comment by ringerc** [comment]
`CREATE INDEX CONCURRENTLY` is a known pain point. It does its own transactions and applies in multiple stages. But BDR's apply process expects apply of a DDL command to complete entirely or fail entirely, not partially succeed. It has no provision to detect and recover from a partially completed `CREATE INDEX CONCURRENTLY` at this time. But if you hit that issue you'll get "index already exists" errors, which isn't what you're seeing here.

Are you sure you didn't run the `CREATE INDEX` with DDL replication disabled? Check `bdr.queued_commands`; is the original `CREATE INDEX` present there?

In any case, creating the index on the other nodes, with ddl rep disabled, to allow the drop to succeed and apply to continue is a sensible solution.

You can, as you noted, also skip over the pending transaction. But that's only safe if you know the only command in it is the DROP INDEX. If the transaction incorporates other changes too, you'd usually have to do manual repair work on each node to apply the other changes from the problem txn and put the nodes back in sync.

A large proportion of operational issues I see reported with BDR tend to come from use of the skip/disable GUCs without sufficient care. In particular, people not understanding why DDL locking is important and turning it off, then breaking their clusters. But this sort of thing is why those options are there - they let you recover from otherwise cluster-breaking problems.

**Comment by ayurkows** [comment]
> Are you sure you didn't run the CREATE INDEX with DDL replication disabled? Check bdr.queued_commands; is the original CREATE INDEX present there?

This is the first time I ever disabled ddl replication in order to fix the issue, so it shouldn't be the case. The issue was resolved by creating the index with ddl replication disabled so that the index was there to be deleted and replication continued and succeeded on all nodes.
