### ISSUE TITLE
BDR: Table 'bdr.bdr_nodes' may be inconsistent after use case of removing a node, then adding a new node

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#50]
In a elasticity test, the system table 'bdr.bdr_nodes' is inconsistent after removing and then adding a new node.
From the recently-added node, the 'node_status' column shows a value of 'o':

-- node 4
```
select * from bdr.bdr_nodes;
     node_sysid      | node_timeline | node_dboid | node_status | node_name |      node_local_dsn      |    node_init_from_dsn    
---------------------+---------------+------------+-------------+-----------+--------------------------+--------------------------
 6132838048147016153 |             1 |      16386 | r           | node1     | port=5598 dbname=bdrdemo | 
 6132838096355400194 |             1 |      16386 | k           | node2     | port=5599 dbname=bdrdemo | port=5598 dbname=bdrdemo
 6132870937724282081 |             1 |      16386 | o           | node4     | port=6001 dbname=bdrdemo | port=5598 dbname=bdrdemo
 6132854400507681900 |             1 |      16386 | k           | node3     | port=6000 dbname=bdrdemo | port=5598 dbname=bdrdemo
```
 However, from another node, the 'node_status' column shows a value of 'i':
```
select * from bdr.bdr_nodes;
     node_sysid      | node_timeline | node_dboid | node_status | node_name |      node_local_dsn      |    node_init_from_dsn    
---------------------+---------------+------------+-------------+-----------+--------------------------+--------------------------
 6132838048147016153 |             1 |      16386 | r           | node1     | port=5598 dbname=bdrdemo | 
 6132838096355400194 |             1 |      16386 | k           | node2     | port=5599 dbname=bdrdemo | port=5598 dbname=bdrdemo
 6132870937724282081 |             1 |      16386 | i           | node4     | port=6001 dbname=bdrdemo | port=5598 dbname=bdrdemo
 6132854400507681900 |             1 |      16386 | k           | node3     | port=6000 dbname=bdrdemo | port=5598 dbname=bdrdemo
(4 rows)
```

---------------
It does seem that the nodes are replicating correctly.  It may mean that the function to update the new node isn't being called?  Or, when the new node4 comes online, it may need to ping the other nodes to say 'I'm ready'.

**Comment by sym39** [comment]
I have a similar problem with only two nodes. After removing a node, then adding it again, the state for node2 is 'i' on one side and 'r' on the other side. However, things seem to work correctly. If I stop then restart the database on both nodes, the state does not change to 'r'. It annoying because one can not use the node_status to check if the nodes are correctly connected together.

To remove then add the node, I do things in the following order (I am not completely sure if I do it on the right way):
Connected on node1:
* call bdr.bdr_part_by_node_names('node2') 
* check the related replication_slot does not exist anymore 
* clean the related replication_identifier 
* clean bdr.bdr_nodes and bdr.bdr_connections information related to node2

Connected on node2:
* call bdr.bdr_part_by_node_names('node1') 
* check the related replication_slot does not exist anymore 
* clean the related replication_identifier 
* clean bdr.bdr_nodes and bdr.bdr_connections information related to node1
* drop the mydb database
* create the mydb database add add btree_gist and bdr extensions
* call bdr.bdr_group_join()

Here the states at the end:

# Node 1
     node_sysid      | node_timeline | node_dboid | node_status |   node_name    |       node_local_dsn                         |       node_init_from_dsn                            
    ---------------------+---------------+------------+-------------+----------------+----------------------------------------------+------------------------------------------------
     6164341399577920820 |             1 |      16416 | r           |     node1     | host=172.27.118.64 port=5432 dbname=mydb | 
     6164348315690684303 |             1 |      27327 | i           |     node2     | host=172.27.118.65 port=5432 dbname=mydb | host=172.27.118.64 port=5432 dbname=mydb

# Node 2
     node_sysid      | node_timeline | node_dboid | node_status |   node_name    |        node_local_dsn                        |          node_init_from_dsn                            
    ---------------------+---------------+------------+-------------+----------------+----------------------------------------------+--------------------------------------------------
     6164341399577920820 |             1 |      16416 | r           |     node1     | host=172.27.118.64 port=5432 dbname=mydb | 
     6164348315690684303 |             1 |      27327 | r           |     node2     | host=172.27.118.65 port=5432 dbname=mydb | host=172.27.118.64 port=5432 dbname=mydb

I notice the following log on node2 that may be related:

    CONFLICT: remote UPDATE on relation bdr.bdr_nodes originating at node 6164341399577920820:1:16416 at ts 2015-06-25 17:14:58.290248+00; row was previously updated at node 0:0. Resolution: last_update_wins_keep_local; PKEY: node_sysid[text]:6164348315690684303 node_timeline[oid]:1 node_dboid[oid]:27327 node_status[char]:c node_name[text]:node2 node_local_dsn[text]:host=172.27.118.65 port=5432 dbname=mydb node_init_from_dsn[text]:host=172.27.118.64 port=5432 dbname=mydb

May be the status was not updated because of this conflict?

PS: Is there another way to check the nodes are correctly connected together?

**Comment by rahulgoel1985** [comment]
Hi, I am also facing the same issue. Did you manage to get pass this error?

**Comment by sym39** [comment]
@rahulgoel1985: I am not sure, but I guess I had this error when the source database is accessed (UPDATE / INSERT in some tables) while I connect the nodes together.
In fact, having some activity on the source database when connecting nodes seems to be a problem with BDR 0.9.1 (SQL interface).
