### ISSUE TITLE
bdr_subscribe is overly fussy about pg_restore version

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#75]
By accident, I happened to have pg_restore v. 9.4.1 on a 9.4.2 server.  This caused bdr_subscribe to fail with this message: 
[ @  @ 2015-05-28 23:27:17.074 GMT]:ERROR:  bdr: failed to find pg_restore relative to binary /usr/lib/postgresql/9.4/bin/postgres or wrong version (expected 9.4.2)

init should still work with a different minor version.

Using git commit c059823e1852ce50def4cbdbef139b0d3389d109
PostgreSQL 9.4.2 from pgdg packages.

**Comment by ringerc** [comment]
Dealing with this requires writing our own command finding logic and version compare logic instead of using core's. Right now we just use `find_other_exec`.

I'm not sure this passes the effort/reward threshold.

**Comment by ringerc** [comment]
There's enough to do that I don't think this merits attention in the forseeable future, so closing as wontfix in the absence of further discussion.

**Comment by jberkus** [comment]
We should at least add it to the documentation, then.

**Comment by ringerc** [comment]
I think I misunderstood this before - it's relating to UDR, and even if packages for UDR are used, a point-release update in the PGDG packages will cause it to fail until/unless a corresponding new UDR package is installed or (if from source) UDR is re-configured and re-built. It's not just an issue with >1 `pg_restore` on the `PATH`.

It'd be nice if `find_other_exec` let us do major-version-only matching, because it looks like it'll be necessary to copy most of that code otherwise.

**Comment by PJMODOS** [comment]
Fixed in HEAD (d28cfc5)
