### ISSUE TITLE
bdr_initial_load lacks documentation, has incorrect help

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#76]
commit c059823e1852ce50def4cbdbef139b0d3389d109

First, bdr_initial_load is used by bdr_subscribe, but not documented anywhere.

Second, bdr_initial_load --help gives this:

```
root@de1c9c0ff7c5:/var/log/postgresql# /usr/lib/postgresql/9.4/bin/bdr_initial_load --help
Usage: bdr_replica --source <dsn> --target <dsn> [--snapshot <name>] --dir /path/to/dir [--jobs N]
<dsn> is a libpq conninfo string, e.g. "host=/tmp post=5433 dbname=xxx"
```

So, first that's the wrong utility name, and second the dsn example has a typo.  

This looks like something I might be able to fix, so mostly putting it on the issues list for later.

**Comment by anarazel** [comment]
On 2015-05-28 16:42:00 -0700, Josh Berkus wrote:
> First, bdr_initial_load is used by bdr_subscribe, but not documented anywhere.

Why would it need to be?

> Second, bdr_initial_load --help gives this:
> 
> root@de1c9c0ff7c5:/var/log/postgresql# /usr/lib/postgresql/9.4/bin/bdr_initial_load --help
> Usage: bdr_replica --source <dsn> --target <dsn> [--snapshot <name>] --dir /path/to/dir [--jobs N]
> <dsn> is a libpq conninfo string, e.g. "host=/tmp post=5433 dbname=xxx"
> 
> So, first that's the wrong utility name, and second the dsn example has a typo.  

Yea, that's obviously wrong.

**Comment by ringerc** [comment]
`bdr_initial_load` pretty much only exists because Pg's dump and restore can't be done over the wire protocol and there's no library-like interface for them. The only reason it's not purely internal is that it's a bit complicated to write the relevant `pg_dump` and `pg_restore` invocations directly in C rather than shell out to do the work. Especially since there's some intention to support `--single-transaction` pipelined loads as an alternative.

Rather than having any user-facing docs for `bdr_initial_load`, the right fix is probably just to just do that work in C, preferably in conjunction with switching to `--schema-only` and doing separate `COPY` ourselves. For bonus fun, this needs to also happen with `CreateProcessEx` and friends on Windows.

**Comment by PJMODOS** [comment]
The right fix for this is definitely to move the logic to C and get rid of the script altogether.

**Comment by ringerc** [comment]
Docs and --help patched, closing. Opened a new issue for the underlying enhancement needed long term.
