### ISSUE TITLE
make it possible for bdr_subscribe to pull only the target tables

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#78]
Feature request:

Replication sets would become much more useful if it was possible for bdr_subscribe to pull only the tables in the target replication sets and their dependencies.  Right now, during initialization bdr_subscribe makes a copy of all objects in the master database.  This prevents UDR from being used in, for example, sharding setups.

I'm aware of how complicated this is; just filing it for later work.  Thanks!

**Comment by ringerc** [comment]
Yep, it's exceedingly complicated to do well, especially since PostgreSQL has stuck stubbornly to having dump support only in a standalone client program that can't be loaded as a library, let alone something invokable from server-side.

We'd have to teach `pg_dump` to do transitive dependency walking so we can say `pg_dump --with-dependencies -t thistable -t thattable ...`. BDR already has a patched `pg_dump` so that we can pass a `--snapshot` from the outside, but that would be a whole new level of invasive.

This would be made significantly easier by a server-side `pg_get_tabledef(...)`, of course.

As a starting point, we're probably first going to do whole-DB `--schema-only` dumps, then `COPY` only the data for tables that are in target replication sets during init, using the snapshot exported by the initial slot. This could also be used for table sync when a table is added to a replication set, which we don't currently support.

This isn't currently a development priority, so setting "future" milestone.

This is certainly an area where patches would be welcome - starting with using `--schema-only` dumps and then `COPY`ing only target tables from an exported snapshot (so we can safely-ish disable FK checks). If this is something you're interested in pursuing, you'd want to use `bdr_copytable` to do the actual `COPY`, and it'd be reasonable in a v1 to do the copy serially from the perdb worker responsible for setup. We'd later want to fork workers to copy tables in parallel, of course.

**Comment by jberkus** [comment]
Craig,

I'm hoping to get a project that would fund work on this specific feature.  We'll see if it comes through.

**Comment by anarazel** [comment]
On 2015-05-29 02:16:10 -0700, Craig Ringer wrote:
> Yep, it's exceedingly complicated to do well, especially since
> PostgreSQL has stuck stubbornly to having dump support only in a
> standalone client program that can't be loaded as a library, let alone
> something invokable from server-side.

Comeon. It's not about being "stubborn" it's about nobody having the
person year available to change that.

> We'd have to teach `pg_dump` to do transitive dependency walking so we
> can say `pg_dump --with-dependencies -t thistable -t thattable
> ...`. BDR already has a patched `pg_dump` so that we can pass a
> `--snapshot` from the outside, but that would be a whole new level of
> invasive.

I actually think that code should be in the database, when defining sets
instead.

> This would be made significantly easier by a server-side `pg_get_tabledef(...)`, of course.

No, it wouldn't. Doesn't help with cross version rep.

Greetings,

Andres Freund

**Comment by jberkus** [comment]
I've been playing with this idea, and I'm thinking that the v1 version of this should simply be a bdr_subscribe which doesn't try to copy the DDL at all.  That is, ala Slony, the user creates the table definitions and dependant objects themselves, and the initial bdr_subscribe copies only the data using COPY.

This means just implementing a 'data' option for bdr_subscribe(synchronize), and avoids initially the necessity of implementing pgdump as functions.  Not that the latter would be a bad thing, but it's a big project.

**Comment by ringerc** [comment]
@anarazel is as usual quite right that function interfaces to dump aren't required for this, and wouldn't help when working across versions. So it's mostly about invoking `pg_dump` with the right options for sets of tables to dump, so it dumps only the wanted tables but includes all non-table objects.

**Comment by jberkus** [comment]
Craig,

Does implementing the 'data' mode look right to you in terms of how to go forward with this?

**Comment by anarazel** [comment]
Hi,

> Does implementing the 'data' mode look right to you in terms of how to go forward with this?

I think that's the wrong way. I don't mind adding a 'data only' mode,
but I think that's just a cheap workaround. But useful for other cases
too.

I plan to work on implementing at least proper partial clone support.

**Comment by jberkus** [comment]
Well, the case I'm concerned about is where multiple databases are replicating into a single database.  Particularly, doing round-robin redundancy for sharding.

**Comment by PJMODOS** [comment]
closing as UDR is deprecated in favour of pglogical
